#include "ExporterRenpy.h"

#include <QFile>
#include <QTextStream>
#include <QStringList>

#include "ScriptFormatter.h"
#include "model/Choice.h"
#include "model/Project.h"
#include "model/StoryNode.h"

ExporterRenpy::ExporterRenpy(Project *project)
    : m_project(project)
{
}

bool ExporterRenpy::exportToFile(const QString &fileName)
{
    if (!m_project) {
        return false;
    }

    QFile file(fileName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    QTextStream out(&file);
    out << "# Generated by Visual Novel Editor\n\n";

    if (m_project->nodes().isEmpty()) {
        return true;
    }

    const QString startId = m_project->nodes().firstKey();
    generateNode(startId, out, 0);
    return true;
}

void ExporterRenpy::generateNode(const QString &nodeId, QTextStream &out, int indent)
{
    if (nodeId.isEmpty() || m_visited.contains(nodeId)) {
        return;
    }

    m_visited.insert(nodeId);
    StoryNode *node = m_project->getNode(nodeId);
    if (!node) {
        return;
    }

    out << "label " << nodeId << ":\n";

    const QStringList lines = node->script().split('\n');
    for (const QString &line : lines) {
        out << ScriptFormatter::indent(indent + 4) << line.trimmed() << '\n';
    }

    if (!node->choices().isEmpty()) {
        out << ScriptFormatter::indent(indent + 4) << "menu:\n";
        for (const Choice &choice : node->choices()) {
            out << ScriptFormatter::indent(indent + 8);
            if (choice.condition.has_value()) {
                out << "if " << choice.condition.value() << ": ";
            }
            out << '"' << choice.text << '"' << ":\n";
            out << ScriptFormatter::indent(indent + 12) << "jump " << choice.targetNodeId << '\n';
        }
    } else {
        out << ScriptFormatter::indent(indent + 4) << "# TODO: define next action\n";
    }

    out << '\n';

    for (const Choice &choice : node->choices()) {
        generateNode(choice.targetNodeId, out, indent);
    }
}
